#!/bin/bash
set -o errexit -o nounset -o pipefail

function globals {
  export LC_ALL=en_US.UTF-8
}; globals

# Calls a function of the same name for each needed variable.
function global {
  for arg in "$@"
  do [[ ${!arg+isset} ]] || eval "$arg="'"$('"$arg"')"'
  done
}

function install_mesos {
  global os_release
  case "$os_release" in
    ubuntu/14.04)      install_with_apt "trusty" ;;
    *)                 err "No support for $os_release at this time." ;;
  esac
}

function install_apt_source {
  echo "deb http://repos.mesosphere.io/ubuntu/ $1 main" |
    as_root tee /etc/apt/sources.list.d/mesosphere.list
  as_root apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  as_root apt-get update
}

function install_with_apt {
  [[ ! -z ${rel-''} ]] && mesos_rel="mesos=${rel}" || mesos_rel="mesos"

  apt_ curl unzip
  install_apt_source $1

  # Fetch Mesos dependencies.
  apt_ git
  apt_ autoconf libtool
  apt_ build-essential python-dev python-boto libcurl4-nss-dev libsasl2-dev maven libapr1-dev libsvn-dev

  # Fetch my branch.
  git clone https://github.com/kaysoky/mesos.git

  # Default build instructions.
  cd mesos
  ./bootstrap
  mkdir build
  cd build
  ../configure --disable-python --disable-java
  make -j8
  make -j8 check
  make install

  apt_ zookeeperd zookeeper zookeeper-bin docker.io marathon chronos

  as_root ln -sf /usr/bin/docker.io /usr/local/bin/docker
  as_root sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io

  # Stop any services.  We don't want to run anything yet.
  as_root service marathon stop
  as_root service chronos stop
  as_root service mesos-master stop
  as_root service mesos-slave stop
}

function apt_ {
  as_root env DEBIAN_FRONTEND=noninteractive aptitude update
  as_root env DEBIAN_FRONTEND=noninteractive aptitude install -y "$@"
}

function as_root {
  if [[ $(id -u) = 0 ]]
  then "$@"
  else sudo "$@"
  fi
}

function os_release {
  msg "Trying /etc/os-release..."
  if [[ -f /etc/os-release ]]
  then
    ( source /etc/os-release && display_version "$ID" "$VERSION_ID" )
    return 0
  fi
  msg "Trying /etc/redhat-release..."
  if [[ -f /etc/redhat-release ]]
  then
    # Seems to be formatted as: <distro> release <version> (<remark>)
    #                           CentOS release 6.3 (Final)
    if [[ $(cat /etc/redhat-release) =~ \
          ^(.+)' '+release' '+([^ ]+)' '+'('[^')']+')'$ ]]
    then
      local os
      case "${BASH_REMATCH[1]}" in
        'Red Hat '*) os=RedHat ;;
        *)           os="${BASH_REMATCH[1]}" ;;
      esac
      display_version "$os" "${BASH_REMATCH[2]}"
      return 0
    else
      err "/etc/redhat-release not like: <distro> release <version> (<remark>)"
    fi
  fi
  if which sw_vers &> /dev/null
  then
    local product="$(sw_vers -productName)"
    case "$product" in
      'Mac OS X') display_version MacOSX "$(sw_vers -productVersion)" ;;
      *) err "Expecting productName to be 'Mac OS X', not '$product'!";;
    esac
    return 0
  fi
  err "Could not determine OS version!"
}

function display_version {
  local os="$( tr A-Z a-z <<<"$1" )" version="$( tr A-Z a-z <<<"$2" )"
  case "$os" in
    redhat|centos|debian) out "$os/${version%%.*}" ;;   # Ignore minor versions
    macosx)               out "$os/${version%.*}" ;;  # Ignore bug fix releases
    *)                    out "$os/$version" ;;
  esac
}

function msg { out "$*" >&2 ;}
function err { local x=$? ; msg "$*" ; return $(( $x == 0 ? 1 : $x )) ;}
function out { printf '%s\n' "$*" ;}

install_mesos
